CHANGELOG.md
build.gradle
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiComponent.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiDeveloper.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizer.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizerSpec.groovy
src/test/resources/org/jenkinsci/gradle/plugins/jpi/bitbucket-pom.xml
src/test/resources/org/jenkinsci/gradle/plugins/jpi/complex-pom.xml
src/test/resources/org/jenkinsci/gradle/plugins/jpi/minimal-pom.xml

Upcoming changes in Gradle 2.3 ([GRADLE-2999](https://issues.gradle.org/browse/GRADLE-2999)) will allow to publish a second artifact without classifier. This enables the Gradle JPI Plugin to publish the plugin JAR together with the JPI file ([JENKINS-25007](https://issues.jenkins-ci.org/browse/JENKINS-25007)).
Publishing a second artifact is only possible with the maven-publish plugin. This pull requests migrates to the maven-publish plugin.
As a consequence the `install`, `deploy` and `uploadArchives` tasks are no longer available for publishing JPI files and have been replaced by the `publishToMavenLocal` and `publish` tasks.
The generated POM also differs. ~~It no longer contains a reference to the Jenkins plugin parent POM and~~ all dependencies have the runtime scope. That should not …

Migration to maven-publish plugin

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy

The `buildDirectory` system property is set for all versions since JenkinsRule and HudsonTestCase also use that property for other purposes.
The fix for [JENKINS-26331](https://issues.jenkins-ci.org/browse/JENKINS-26331) will be included in 1.597, so we need to care about the `target` directory only for coreVersions < 1.597.

set buildDirectory system property for Jenkins test harness

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiHplManifest.groovy

With this change running the server task on the Job-Dsl-Plugin works again.

[FIXED JENKINS-26377] Use classpath from JPI-Task instead of runtimeClasspath

---

CHANGELOG.md
config/codenarc/rules.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifestSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPluginSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizerSpec.groovy
src/test/resources/org/jenkinsci/gradle/plugins/jpi/complex-pom.xml

Added `configureRepositories` option to be able to skip configuration of repositories.
See [JENKINS-17130](https://issues.jenkins-ci.org/browse/JENKINS-17130).

Added configureRepositories Option

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPluginSpec.groovy

Added `configurePublishing` option to be able to skip configuration of publications or repositories for the Maven Publishing plugin.

Added configurePublishing Option

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/Jpi.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifest.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifestSpec.groovy

In order to make the Job DSL plug-in useable from other plug-ins, especially in their integration tests using the JenkinsRule, the JAR needs the Manifest information.
See [JENKINS-27994](https://issues.jenkins-ci.org/browse/JENKINS-27994) for more context.

JENKINS-27994 Adding the manifest in the JAR

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/TestDependenciesTask.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/TestDependenciesTaskIntegrationSpec.groovy
src/test/resources/org/jenkinsci/gradle/plugins/jpi/resolveTestDependencies.gradle

... instead copying to the `plugins` directory to mimic the behavior of the Maven HPI plugin

copy plugin dependencies to test-dependencies directory

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPluginSpec.groovy

I already have a task called "install" on my Gradle task graph, and I don't need the "install" task from this plugin when I have configured publishing to false.

Don't apply MavenPublishPlugin if configurePublishing is false.

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiLicense.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizer.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiLicenseSpec.groovy

Added the ability to specify a license that will be in the generated pom.

Add licenses for the pom generation.

---

README.md

Gradle 4's split classes folders does not work with SezPoz. While this should be solved in the plugin, for now it should be at least documented along with workarounds.

Explain incompatibility and solutions for Gradle 4

---

README.md

The update adds documentation about the --no-daemon option of gradle that prevents it from spawning an extra process to run Jenkins.

Update README.md section for debugging

---

gradle/wrapper/gradle-wrapper.properties
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/GenerateTestHpl.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifest.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiHplManifestSpec.groovy

Starting from Gradle 4.0, the classes for Java and Groovy are compiled into two different classes directories. The Gradle JPI plugin has problems when the Plugin classes are split between those two directories.
This PR aims to fix the problems. It would require plugin users to also use Gradle 4.+.

Add support for Gradle 4.0 split classes dirs

---

README.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/ServerTask.groovy

A new jenkinsServer configuration is introduced that allows to install
extra plugins with the use of the server task.

Add new configuration to install plugins for server task

---

.gitignore
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtensionSpec.groovy

[JENKINS-48353](https://issues.jenkins-ci.org/browse/JENKINS-48353)
junit-dep is long since deprecated and causes issue when using newer junit 4.12 that now has 
the Timeout.seconds method.

[Jenkins-48353] removes junit-dep on newer releases

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtensionSpec.groovy

This will resolve the issue reported in [JENKINS-47988](https://issues.jenkins-ci.org/browse/JENKINS-47988)

[JENKINS-47988] update test harness version on core version >= 2.64

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/LicenseTask.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizerSpec.groovy

This PR addresses [JENKINS-51622](https://issues.jenkins-ci.org/browse/JENKINS-51622)
* `org.gradle.execution.TaskGraphExecuter` is no longer present in Gradle 4.8. I've replaced it with [`org.gradle.api.execution.TaskExecutionGraph`](https://docs.gradle.org/current/javadoc/org/gradle/api/execution/TaskExecutionGraph.html)
* `org.gradle.internal.component.local.model.DefaultProjectComponentIdentifier` has moved as of Gradle 4.8. I've replaced this with the public [`org.gradle.api.artifacts.component.ProjectComponentIdentifier`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/component/ProjectComponentIdentifier.html)
* MavenPomFileGenerator has a changed API after Gradle 4.7, so this works in both scenarios.

JENKINS-51622: Backwards-Compatible Changes for Gradle 4.8

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/ServerTask.groovy

Otherwise when running `gradle server` the first time with Jenkins 2.x,
the user has to follow manual setup steps in the browser.
That's also the default setting in plugin-pom:
- https://github.com/jenkinsci/plugin-pom/blob/plugin-3.32/pom.xml#L93-L94
- https://github.com/jenkinsci/plugin-pom/blob/plugin-3.32/pom.xml#L678-L680

Skip Jenkins wizard in server task

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifest.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/AbstractManifestIntegrationSpec.groovy

Using Gradle's built-in [targetCompatibility property](https://docs.gradle.org/current/userguide/java_plugin.html#other_convention_properties) to populate this value for [Jenkins Java 11 Support](https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines).
This updates the generated `META-INF/MANIFEST.MF` to contain entries like:
`Minimum-Java-Version: 1.8` or `Minimum-Java-Version: 11`.
Related PRs:
* jenkinsci/jenkins#3016
* https://github.com/jenkinsci/jenkins/pull/3842
@jenkinsci/java11-support would you be able to take a look at this PR?

Add Minimum-Java-Version to Manifest

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtensionSpec.groovy

Previously the rootDir was used as parent for the work directory. This
led to the situation where a subproject containing a jenkins plugin put
the work directory at the top of the project hierarchy. This becomes
especially problematic when several jenkins plugins are managed from one
root projects.
This change uses `project.projectDir` instead which will be the same as
`project.rootDir` for projects without sub projcts but will be the
actual project directory for nested projects.

Put work directory inside project directory

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

Now the classes packaged as JAR file which is put into the JPI file under `WEB-INF/lib` instead of all the classes under `WEB-INF/classes`. Dependencies are still correctly put under `WEB-INF/lib` as JAR files.
But I am not sure if this solves the issue 100% or if some corner cases are missed.

[JENKINS-54064] Bundle classes as JAR file into HPI file

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPluginSpec.groovy

The following output was shown when running `gradle help --warning-mode all` for a Jenkins plugin that is based on this one:
> The ... property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the ... property instead.
This is to resolve these warnings.

Handle deprecated Gradle properties of "jar" and "war" task

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

This issue was introduced in commit 7a565d3d51b400e67ce5643e3f71b9113c194296, when lazily registering the task.
Without this fix the `build/generated-resources/test/the.hpl` is not generated and therefore `org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive` from `InjectedTest` is failing.

Fix generate-test-hpl task dependency for running tests

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

Currently, this would produce a module metadata file which can't be
consumed by downstream projects, since it doesn't contain any
dependencies and only the hpi variant and not jar variant.
Until this is fixed, Gradle module metadata shouldn't be published.
I realized this when publishing version 1.36 of the Jenkins `gradle-plugin`: https://github.com/jenkinsci/gradle-plugin/pull/94#issuecomment-570720014.

Do not publish Gradle module metadata

---

config/codenarc/rules-test.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

Remove the CodeNarc line length limit for tests.
See https://github.com/jenkinsci/gradle-jpi-plugin/pull/127#issuecomment-570798985

No line length limit in tests

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifest.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/AbstractManifestIntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/IntegrationSpec.groovy

So version constraints from e.g. BOMs can take effect.
It would be nice to have a better way to filter out platform dependencies, or anything different than JPI variants I suppose.

Use resolved dependencies for writing manifest

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiHplManifest.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiHplManifestSpec.groovy

This is a follow up to #132 that unintentionally broke some classpath setups. This should fix:
- https://github.com/jenkinsci/gradle-jpi-plugin/commit/c21a7a10fbfa017d132e002d4024233aa8cecbd6#r37121475
- https://github.com/jenkinsci/gradle-jpi-plugin/pull/132#issuecomment-582327165

Fix classpath issues

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPluginSpec.groovy
src/test/resources/org/jenkinsci/gradle/plugins/jpi/compile-dependencies-module.json
src/test/resources/org/jenkinsci/gradle/plugins/jpi/compile-dependencies-with-excludes-module.json
src/test/resources/org/jenkinsci/gradle/plugins/jpi/minimal-module.json
src/test/resources/org/jenkinsci/gradle/plugins/jpi/optional-plugin-dependencies-module.json
src/test/resources/org/jenkinsci/gradle/plugins/jpi/plugin-dependencies-module.json

Hi @sghill 
I was going through https://github.com/jenkinsci/gradle-jpi-plugin/issues/138 again and then realized that maybe what would be nice is to avoid creating sources/javadoc jar tasks if `configurePublishing` is `false`.
The current experience is that if you have `configurePublishing` as `false`, the `mavenJpi` publication won;'t be created, avoiding `JpiPomCustomizer`. However, `javaPluginExtension.withSourcesJar()` and  `javaPluginExtension.withJavadocJar()` configure publications so it goes against the nature of the `configurePublishing`. 
Do you think this change would make .sense? The changes contain modification to the expected module.json files because the order of the `variants` changed with this modification

sources and javadocs jar should only be configured when configurePublishing is enabled

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiTaskRegistrationIntegrationSpec.groovy

Hi @sghill,
This is for https://github.com/jenkinsci/gradle-jpi-plugin/issues/141
Prevent: 
```
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with type class org.jenkinsci.gradle.plugins.jpi.JpiPlugin has not been used.
at org.gradle.api.internal.plugins.DefaultPluginContainer.getPlugin(DefaultPluginContainer.java:140)
at org.gradle.api.plugins.PluginContainer$getPlugin$2.call(Unknown Source)
at org.jenkinsci.gradle.plugins.jpi.JpiPlugin$_configureJpi_closure10.doCall(JpiPlugin.groovy:178)
``` 
This happened when other plugins create the `jpi` task during configuration phase.

JpiPlugin: Do not attempt to get the plugin that is just being applied

---

build.gradle.kts

More info in https://blog.gradle.org/plugin-portal-update

Mandatory upgrade for plugin portal publishing

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/DependencyAnalysis.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/LicenseTask.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/LicenseTaskSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/ServerTaskSpec.groovy
src/test/resources/org/jenkinsci/gradle/plugins/jpi/licenseInfoWithKotlin.gradle
src/test/resources/org/jenkinsci/gradle/plugins/jpi/licensesWithKotlin.xml

This plugin creates detached configurations in three places. Two of them will fail if the Kotlin plugin is applied because we cannot find a matching variant ([Louis describes the underlying issue here](https://youtrack.jetbrains.com/issue/KT-31641#focus=streamItem-27-3698024.0-0)). One way to fix this is with [a workaround mentioned in YouTrack for Kapt](https://youtrack.jetbrains.com/issue/KT-31641#focus=streamItem-27-3666505.0-0).
This workaround is not ideal since we have to modify two places to behave differently if another plugin is applied. @wolfs or @jjohannes would you mind looking at this?
Fixes #153.

Workaround: Apply usage attribute if Kotlin plugin applied

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/internal/DependencyLookup.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/internal/DependencyLookupSpec.groovy

Some tests require sezpoz's annotation processing. Today this must be added explicitly. This change adds sezpoz as an annotation processor for tests automatically.
cc @rahulsom

Add sezpoz to testAnnotation configuration by default

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy

I had a number issues applying this upgrade from 0.38.0 because I needed
to build against Gradle 7.3.1
Specifically the main error I received was:
```
* What went wrong:
A problem occurred evaluating project ':jenkins-skylab-plugin'.
> Failed to apply plugin class 'org.jenkinsci.gradle.plugins.manifest.JenkinsManifestPlugin'.
> Could not create task ':jenkins-skylab-plugin:generateJenkinsManifest'.
> Extension of type 'JpiExtensionBridge' does not exist. Currently registered extension types: [ExtraPropertiesExtension, EclipseModel, IdeaModel, ProcessorsExtension, BlacklistExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaPluginExtension, JavaToolchainService, TestingExtension, BaselineJavaVersionExtension, GroovyRuntime]
```
Which …

Fix a number of initialization order issues with 0.43.0

---

.github/workflows/ci.yml
.github/workflows/regression.yml

https://github.com/jenkins-infra/helpdesk/issues/3176
The change proposed takes care of the Node 12 -> 16 warning too, see https://github.com/jenkinsci/gradle-jpi-plugin/actions/runs/3307997015 for reference.

Address `set-output` deprecation

---

README.md
src/main/kotlin/org/jenkinsci/gradle/plugins/manifest/GenerateJenkinsManifestTask.kt
src/test/groovy/org/jenkinsci/gradle/plugins/manifest/GenerateJenkinsManifestTaskIntegrationSpec.groovy

This PR adds a flag that allows to opt-out from adding the timestamp to the `-SNAPSHOT` version in the Jenkins manifest file. Since the default value for the new flag is `true` there are no changes to the build. Users have to configure it explicitly. As mentioned in the [comment](https://github.com/jenkinsci/gradle-jpi-plugin/blob/master/src/main/kotlin/org/jenkinsci/gradle/plugins/manifest/GenerateJenkinsManifestTask.kt#L69) the current behavior doesn't allow Gradle to cache the results and causes all the dependent tasks always to be executed.

Add a flag to disable adding timestamp to the SNAPSHOT version

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/ConfigurePublishingIntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

This fixes https://github.com/jenkinsci/gradle-jpi-plugin/issues/215.
It just adds a new Maven repository named `jenkinsIncrementals` with default url of `https://repo.jenkins-ci.org/incrementals`. The url can be tweaked with the extension:
```
jenkinsPlugin {
incrementalsRepoUrl = '...'
}
```
Note that this does not enforce a generated version to publish to the incrementals repository. To do so see https://github.com/jenkinsci/gradle-jpi-plugin/pull/218

Add Jenkins "incrementals" binary repository

---

README.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/ConfigurePublishingIntegrationSpec.groovy

Previous [PR](https://github.com/jenkinsci/gradle-jpi-plugin/pull/219) fixing https://github.com/jenkinsci/gradle-jpi-plugin/issues/215 added incrementals repository support by publishing to both regular and incrementals repository by default 
This PR basically removes the dependency of `publish` to `publishMavenJpiPublicationToJenkinsIncrementalsRepository` so instead one should call directly `publishMavenJpiPublicationToJenkinsIncrementalsRepository` to publish to incrementals.

Do not publish to incrementals by default

---

README.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/CheckstylePluginSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JacocoPluginSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/SpotBugsPluginSpec.groovy

This avoids applying the plugin(s) if not explicitly required by exposing functions instead of boolean flags.
See original discussion https://github.com/jenkinsci/gradle-jpi-plugin/pull/220#issuecomment-1466458399

Enable quality check plugins with functions

---

README.md
src/main/java/org/jenkinsci/gradle/plugins/jpi/GitVersionExtension.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GenerateGitVersionTask.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GitVersionGenerator.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/version/GenerateGitVersionTaskSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/version/GitVersionGeneratorSpec.groovy

This is a follow up of https://github.com/jenkinsci/gradle-jpi-plugin/issues/215 that is not sufficient to publish incrementals when running on ci.jenkins.io, since it would require passing credentials.
Instead some plumbing is required in https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildPluginWithGradle.groovy like it's done on the Maven side:
* Running a build to generate the version file containing the sanitize version (`a`, `b` not allowed)
* Running the build overriding the version with `-Pversion` and archiving the resulting artifacts
* Call `infra.maybePublishIncrementals()` that should eventually caused an external service to pull the artifacts and publish them on Artifactory
This PR adds the necessary hooks to achieve this:
* one additional option is …

Add some utilities to support incrementals via Jenkins infra pipeline-library

---

README.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizer.groovy
src/main/java/org/jenkinsci/gradle/plugins/jpi/GitVersionExtension.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GenerateGitVersionTask.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GitVersionGenerator.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPomCustomizerIntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/version/GenerateGitVersionTaskSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/version/GitVersionGeneratorSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/version/Util.groovy
src/test/resources/org/jenkinsci/gradle/plugins/jpi/complex-pom.xml

This is another follow up of https://github.com/jenkinsci/gradle-jpi-plugin/issues/215 that is not sufficient to publish incrementals when running on ci.jenkins.io (hopefully the last one ?).
* It requires first to have `<tag>...</tag>` set in the published pom with the full git hash. 
This PR changes the `generateGitVersionTask` to also set the full Git hash in the `version.txt` in addition to the formatted one. It also adds a`scmTag` property to the `JpiExtension` that can be set via a Gradle property. Eventually the https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildPluginWithGradle.groovy will do something like 
`-PscmTag=${versionFile.readLines()[1]}`
* Optionally users should be able to add a version prefix to the generate version, like a "major.minor" for …

Add again some utilities to support incrementals via Jenkins infra pipeline-library 

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

See https://github.com/jenkinsci/plugin-pom/pull/415
Sets the `-parameters` option to javac, aligning with plugins built with maven-hpi-plugin.
- Unit test included
- Manually tested: built `gradle-plugin` with a dev version of `gradle-jpi-plugin`, ensured that the `o.k.s.BytecodeReadingParanamer#lookupParameterNames: Looking up parameter names for public hudson.util.FormValidation hudson.plugins.gradle.enriched.EnrichedSummaryConfig.doCheckHttpClientTimeoutInSeconds(int); update plugin to a version created with a newer harness` are gone

Use `-parameters` for JavaCompile tasks

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy

Looks like a copy-pasta error, someone set minimum gradle version to 7.1 but the error recommends using 6.3+ :-(
Its error message text - nothing to test

Fix misleading error message

---

.github/workflows/ci.yml
.github/workflows/regression.yml

The default branch of this repository was updated to `main`, but required workflows were left activating on PRs to the previous name.

:wrench: Update workflow config for new default branch

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/Jdk17Plugin.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/JpiExtensionBridge.java

Addresses #243.
Adds selectively to `generatedJenkinsTest` and `test`, so any tests introduced by users (such as `acceptanceTest`) do not automatically get this behavior.
Opens are user-configurable by adding to, clearing, or modifying the `ListProperty` in the extension.

✨ `--add-opens` for JDK 17+

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/DependencyLookup.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/Jdk17Plugin.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/JpiExtensionBridge.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/internal/DependencyLookupSpec.groovy

Discovered while testing #243. Followup to #244.
Plugins that define Jenkins test-only features, like an `echo` step, need the annotation processor to run. Including this dependency allows it to happen.

🔨 Add `jenkins-core` to `testAnnotationProcessor`

---

src/main/java/shaded/hudson/util/VersionNumber.java

This shows up as a warning during the build.
Though the method is deprecated, it's worth documenting it.

docs: Add missing javadoc

---

config/codenarc/rules-test.groovy

This seems to be a behavior change in Gradle 8.
This change brings in all the config from rules.groovy into rules-test.groovy and appends what was in rules-test.groovy on it.
On Gradle 8, it used to fail with
```
> Task :codenarcTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':codenarcTest'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CodeNarcAction
> java.io.FileNotFoundException: rules.groovy (No such file or directory)
```

chore: Do not reference rules.groovy in rules-test.groovy

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

This allows dependencies to be specified without version and resolved later.
Prior to this change, the manifest contained the unresolved version of dependent plugins.
This change puts the resolved version there.
Depends on #267

feat: Support dependency recommenders

---

build.gradle.kts

The plugin doesn't test correctly with Gradle 8, but this publishes correctly with Gradle 7 while allowing being included in a Gradle 8 build without needing code changes.

chore: Make build compatible with Gradle 8

---

src/main/java/hudson/Extension.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/DependencyAnalysisResult.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/GitVersionExtension.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/core/ArchiveExtensions.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/core/PluginDeveloperSpec.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/core/PluginLicenseSpec.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/deployment/CreateVersionlessLookupTask.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/BackwardsCompatiblePluginDevelopers.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/BackwardsCompatiblePluginLicenses.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/DependenciesPlugin.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/DependencyLicenseValidator.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/internal/DependencyLookup.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/verification/CheckOverlappingSourcesTask.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GenerateGitVersionTask.java
src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GitVersionGenerator.java

The javadoc task complains about missing javadocs otherwise. It's a warning, but it is a distraction.

docs: Add missing javadocs

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigurePrepareServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

The version number is hard to remove, but can be cleaned up separately.

feat: Make plugin dependencies work with multimodule plugins

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigurePrepareServerAction.java

We had a bug when you had a dependency called `foo-1.0.2.jpi` and another one called `bar-1.0.jpi`.
The older behavior would process the rename rule for `-1.0 -> EMPTY` first and then `-1.0.2 -> EMPTY`.
That replaced `bar-1.0.jpi` with `bar.jpi`.
But failed with foo and left us with `foo.2.jpi`.
Gradle stores a list of replacements on the same sync object.
This change stores full names as replacements rather than just versions.

fix: Rename JPI files correctly

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java

We sometimes see this exception
```
2025-05-24 17:36:08.729+0000 [id=42]        WARNING hudson.model.Queue#load: Failed to load the queue file /Users/rsomasunderam/src/bb/CISYS/nflx-webservice-api-plugin/work/queue.xml
java.lang.ClassNotFoundException: com/ctc/wstx/stax/WstxInputFactory
```
Fixing it requires adding this to dependencies
```
serverTaskClasspath "org.codehaus.woodstox:wstx-asl:3.2.7"
```
To support that, we need the `serverTaskClasspath` to support such a mode of execution.

feat: Allow customizing serverTaskClasspath

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigureTestServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/PortAllocationService.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java

Adding a shared port allocation service to help make finding free port more reliable.
Did not add any new tests as port allocation service replaces old find free port function. Both are essentially finding a free port but one uses a shared build service. Build is passing.

Adding shared port allocation service

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigureJpiAction.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

Filter out jar files from the JPI classpath that are already provided by JPI plugin dependencies, even when those same jars are also needed as transitive dependencies of other non-JPI dependencies.
This ensures that when a JPI plugin provides a library (like Jackson) and another dependency also transitively depends on the same library, the library jars are not duplicated in the final JPI package.

fix: exclude transitive jar dependencies provided by JPI plugins
