CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/Jpi.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiHplManifest.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifest.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/ServerTask.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiHplManifestSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiManifestSpec.groovy

extending java.util.HashMap causes problems, so it has been replaced by java.util.jar.Manifest

support Java 8

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy

create (for coreVersion < 1.592) and clean target directory used by org.jvnet.hudson.test.WarExploder

target directory

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtensionSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPluginSpec.groovy

Add a JAR dependency for each HPI/JPI dependency to the testCompile configuration.

JENKINS-17129

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/LocalizerTask.groovy

https://issues.jenkins-ci.org/browse/JENKINS-27451

[JENKINS-27451] localize only Message.properties files

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy

... to be able to use @WithPlugin in tests

copy plugin dependencies to test resources output directory

---

CHANGELOG.md
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy

[JENKINS-31451] copy HPI/JPI dependencies from jenkinsTest configuration

---

build.gradle.kts

Refine build script

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/GenerateTestHpl.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiPlugin.groovy
src/main/groovy/org/jenkinsci/gradle/plugins/jpi/ServerTask.groovy

These are minor changes to slightly improve the code.

Refactoring

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtension.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiExtensionSpec.groovy

This is to get the latest features & fixes.

Upgrade jenkins-test-harness

---

src/main/groovy/org/jenkinsci/gradle/plugins/jpi/JpiVariantRule.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/JpiIntegrationSpec.groovy

Hi @sghill, 
This fixes https://github.com/jenkinsci/gradle-jpi-plugin/issues/142

Jpi variant rule/support ivy module resolve metadata

---

src/main/java/hudson/Extension.java

fixes #199 by updating the minimal clone of `hudson.Extension` present in this plugin.

Update the clone of `hudson.Extension` in this plugin to the latest in Jenkins core

---

Jenkinsfile
src/test/java/org/jenkins-ci/tools/Junit4DummyTest.java

Let's build this tool on Jenkins' public infra too.

Add Jenkinsfile

---

README.md

Forgot to update the README with the [previous PR](https://github.com/jenkinsci/gradle-jpi-plugin/pull/222) changing the way to enable quality checks.

Fix README check snippet

---

src/main/java/org/jenkinsci/gradle/plugins/jpi/version/GitVersionGenerator.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/version/GenerateGitVersionTaskSpec.groovy

Adresses comment from previous PR https://github.com/jenkinsci/gradle-jpi-plugin/pull/225#issuecomment-1528197908.
Also adds a small correction in a test to better reflect how it will be used in pipeline-library.

Fix line feed when generation version file

---

.gitignore

chore: Ignore bin directory

---

.editorconfig

This should help IDEs be mostly consistent in formatting without being too strict.

chore: Add editorconfig

---

.github/workflows/ci.yml
.github/workflows/regression.yml
Jenkinsfile
build.gradle.kts
src/main/java/org/jenkinsci/gradle/plugins/jpi/server/JenkinsServerTask.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/ConfigureRepositoriesIntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/server/JenkinsServerTaskSpec.groovy

This will become a requirement for upgrading gradle

chore: Use JDK 17 to build

---

src/test/groovy/org/jenkinsci/gradle/plugins/jpi/IntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/IntegrationTestHelper.java

This allows new tests to be written in Java with JUnit5.

refactor: Extract Gradle bits out of IntegrationSpec

---

build.gradle.kts
gradle/libs.versions.toml
src/main/java/org/jenkinsci/gradle/plugins/jpi2/PrepareServerTask.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/IntegrationTestHelper.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/RandomPortProvider.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

This tries to be as simple as possible.

feat: Add a V2 JPI Plugin

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java

refactor: Break down to smaller methods

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java

Also, default it when not specified.
Stacked on #265

refactor: Extract method for jenkins.version property

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

This causes classes annotated with `@Extension` to be recognized using SPI in a way Jenkins loads them correctly.
Depends on #266

feat: Configure sezpoz

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

feat: Add dependency on core in testImplementation

---

build.gradle.kts
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigureJpiAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigurePrepareServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/HpiMetadataRule.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ManifestAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/PomBuilder.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/SezpozGroovyAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/SezpozJavaAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java
src/test/resources/org/jenkinsci/gradle/plugins/jpi2/compileClasspath.txt
src/test/resources/org/jenkinsci/gradle/plugins/jpi2/runtimeClasspath.txt

There are no more custom configurations - `api`, `implementation`, `compileOnly`, and `runtimeOnly` now handle `jpi`/`hpi` dependencies.

feat: Further simplify V2 plugin

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigureTestServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ServerAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java

This will run the `server` task as a test.
It can be made a dependency of `check` in a jenkins plugin to ensure `server` works after any change.

feat: Add `testServer` task

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java
src/test/resources/org/jenkinsci/gradle/plugins/jpi2/runtimeClasspath.txt

fix: Make runtimeClasspath resolve consistently with jenkins core

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ArtifactType.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigureJpiAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/HpiMetadataRule.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/ManifestAction.java
src/main/java/org/jenkinsci/gradle/plugins/jpi2/V2JpiPlugin.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/IntegrationSpec.groovy
src/test/groovy/org/jenkinsci/gradle/plugins/jpi/IntegrationTestHelper.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java
src/test/resources/org/jenkinsci/gradle/plugins/jpi2/compileClasspath.txt
src/test/resources/org/jenkinsci/gradle/plugins/jpi2/runtimeClasspath.txt

This allows us to make configurations always use JAR or always use DEFAULT packaging.

feat: Add variant and attribute for default artifact

---

src/main/java/org/jenkinsci/gradle/plugins/jpi2/ConfigurePrepareServerAction.java
src/test/groovy/org/jenkinsci/gradle/plugins/jpi2/V2IntegrationTest.java

Drop versioning from artifacts
